name: Node Build and Deploy

on: 
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v5.1.0
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ format('{0}{1}',secrets.REMOTE_TARGET,'_copy') }}
          EXCLUDE: "/public/, /node_modules/"
          SCRIPT_AFTER: |
            rm -rf ${{ secrets.REMOTE_TARGET }} && \
            cp -r ${{ format('{0}{1}',secrets.REMOTE_TARGET,'_copy') }} ${{ secrets.REMOTE_TARGET }} && \
            rm -rf ${{ format('{0}{1}',secrets.REMOTE_TARGET,'_copy') }}
